#指定初始的 book 數據，代替數據庫
product:
  books:
    - isbn: B001
      name: java
      author: lisi
    - isbn: B002
      name: tomcat
      author: zhangsan
    - isbn: B003
      name: jvm
      author: zhouxing

#訪問路徑
server:
  servlet:
    context-path: /api

#開啟使用 RFC7807
spring:
  mvc:
    problemdetails:
      enabled: true